urls:
  - short: abc
    long: https://google.com
  #- short: foo
  #  long: https://pickardayune.com

hosts:
  - name: "example-host"
    urls:
      - short: host-specific
        long: https://duckduckgo.com
